import type { Dict } from "./ru";

export const en: Dict = {
  meta: {
    title: "brain — the tutor that knows what you don't",
    desc: "Gap diagnostics, a personal plan, a live exam score forecast and an ELO rating. A free AI platform for school students in Kazakhstan.",
  },
  nav: {
    dashboard: "Dashboard",
    topics: "Topics",
    leaderboard: "League",
    teacher: "For teachers",
    parent: "For parents",
    profile: "Profile",
    start: "Get started",
    home: "Home",
  },
  common: {
    continue: "Continue",
    back: "Back",
    next: "Next",
    skip: "Skip",
    done: "Done",
    cancel: "Cancel",
    save: "Save",
    add: "Add",
    close: "Close",
    open: "Open",
    min: "min",
    hour: "h",
    points: "pts",
    day: "d",
    today: "today",
    demo: "Demo mode",
    elo: "ELO",
    streak: "streak",
    level: "level",
    correct: "Correct",
    wrong: "Wrong",
    of: "of",
    loading: "Loading…",
  },
  landing: {
    badge: "for school students in Kazakhstan, grades 7–12",
    h1a: "The tutor that knows",
    h1b: "what you don't",
    sub: "brain finds your gaps in 15 minutes, builds a personal plan and walks you to your goal every day — UNT, olympiad or simply solid grades.",
    ctaPrimary: "Take the diagnostic",
    ctaSecondary: "View demo",
    marquee: ["UNT", "Algebra", "Diagnostics", "ELO rating", "Knowledge map", "Streaks", "Score forecast", "Geometry", "Personal plan"],
    demoCard: {
      forecast: "UNT forecast",
      forecastVal: "31 / 50",
      forecastDelta: "+6 this week",
      mapTitle: "Knowledge map",
      eloTitle: "Your ELO",
      eloDelta: "+24 today",
    },
    stepsTitle: "How it works",
    steps: [
      { t: "Tell it what you're aiming for", d: "UNT, olympiad or the school curriculum. Not sure? The advisor asks a few questions and helps you decide." },
      { t: "Take a 15-minute test", d: "Adaptive diagnostics: questions adjust to your answers and pinpoint the weak spots." },
      { t: "Get a personal plan", d: "Not \"read chapters 1–10\" — specific topics and problems at exactly your level." },
      { t: "Level up every day", d: "A short check-in every 4 days refreshes the plan. Progress, ELO and the score forecast grow in front of you." },
    ],
    featTitle: "Not a pile of materials.",
    featTitle2: "A trainer that thinks.",
    features: [
      { t: "Knowledge map", d: "Every topic is a cell on the map. Master it and it lights up orange. Gaps are visible at a glance, no spreadsheets." },
      { t: "Score forecast", d: "After every answer the platform recalculates your expected score. Not \"find out at the exam\" — right now." },
      { t: "Progress that never burns", d: "Switched tracks from CS to physics? Everything you already know counts. Nothing starts over." },
      { t: "ELO, like in chess", d: "Solve a problem above your level and your rating climbs faster. Your friend is at 1500? Catch up." },
      { t: "Streaks and hours", d: "Hours in a game are bragging rights. Hours in learning now are too. Streak, time on task — all visible." },
      { t: "Teacher panel", d: "Teachers see class progress and weak topics, and can hand out assignments. Zero paperwork." },
    ],
    editTitle: "It's not a course.",
    editTitle2: "It's a coach.",
    editBody: "A course is the same for everyone. A coach watches what works for you and what doesn't — and changes the plan. brain does the same: the adaptive algorithm rebuilds your program after every answer, not once a term.",
    editStats: [
      { v: "15 min", l: "to your first knowledge map" },
      { v: "3", l: "interface languages" },
      { v: "24/7", l: "reachable from any village or city" },
      { v: "0 ₸", l: "for students" },
    ],
    gamTitle: "Learning you actually",
    gamTitle2: "want to rank up in",
    gamBody: "Your rating grows for solved problems — faster when the problem is above your level. The streak won't let you skip a day. And study hours are your \"hours played\", except these actually pay off.",
    gamLadder: "Your school's league",
    rolesTitle: "For teachers and parents",
    roleTeacher: { t: "Teacher panel", d: "Whole-class progress on one screen: whose topics are slipping, who hasn't shown up lately. Assignments in two clicks.", cta: "Open the panel" },
    roleParent: { t: "Parent digest", d: "Once a week — short and human: what your kid figured out, where they're stuck, what's next. No pedagogy jargon.", cta: "Sample digest" },
    ctaTitle: "Your first knowledge map — 15 minutes away",
    ctaSub: "No payment, no install, runs even on an old phone.",
    footer: {
      made: "Made in Kazakhstan",
      forWho: "for school students, grades 7–12",
      product: "Product",
      rights: "brain, 2026",
    },
  },
  start: {
    title: "Let's get acquainted",
    nameLabel: "What's your name?",
    namePh: "Name",
    gradeLabel: "What grade are you in?",
    gradeSuffix: "grade",
    goalLabel: "What are we preparing for?",
    goals: {
      ent: { t: "UNT", d: "profile math, a plan that runs to exam day" },
      olymp: { t: "Olympiad", d: "non-standard problems, high difficulty" },
      school: { t: "Boost school grades", d: "close the gaps and solve with confidence" },
      sat: { t: "SAT", d: "Math and Reading & Writing, forecast out of 1600" },
      ielts: { t: "IELTS", d: "Reading, Writing and vocabulary, band forecast" },
    },
    unsure: "Not sure what to pick",
    examDateLabel: "Exam date (if you know it)",
    startDiag: "To the diagnostic",
    subjectLabel: "Subject",
    subjectMath: "Mathematics",
    subjectSoon: "soon",
    langLabel: "Learning language",
  },
  consult: {
    title: "Advisor",
    intro: "Hi! I'll help you pick a goal. A couple of quick questions and I'll suggest where to start.",
    q1: "What grade are you in?",
    q1a: ["7–8", "9–10", "11–12"],
    q2: "Taking an exam within a year?",
    q2a: ["Yes, the UNT", "Not yet"],
    q3: "Which sounds more like you?",
    q3a: ["I want a high score and a grant", "I love tricky starred problems", "I just want to understand the school program"],
    recPrefix: "My recommendation:",
    recWhy: {
      ent: "Every month before the UNT counts: we'll start with diagnostics and a plan built around exam topics.",
      olymp: "You'll enjoy the higher difficulty — let's take the olympiad track.",
      school: "We'll start with the foundation: close the school-program gaps, then aim higher.",
      sat: "For studying abroad we'll take SAT: algebra, data and the Reading & Writing section.",
      ielts: "For a language certificate we'll take IELTS: Reading, Writing structure and academic vocabulary.",
    },
    accept: "Take this goal",
    other: "I'll choose myself",
  },
  diag: {
    title: "Diagnostic",
    sub: "About 10 questions. Difficulty adapts to your answers — it's fine if it gets hard.",
    begin: "Let's go",
    qOf: "Question",
    difficulty: "Difficulty",
    resultTitle: "Done. Here's your map",
    resultElo: "Starting ELO",
    resultForecast: "UNT forecast (math)",
    resultForecastNote: "out of 50 profile-subject points",
    toPlan: "See the plan",
    skipNote: "If you really don't know — hit \"no idea\", that's a signal too.",
    dontKnow: "No idea",
  },
  dash: {
    hello: "Hey",
    yourPlan: "Your plan for today",
    weakTitle: "Weak spots",
    mapTitle: "Knowledge map",
    mapLegend: { strong: "mastered", mid: "in progress", weak: "gap", none: "not started" },
    forecast: "Score forecast",
    forecastUnit: "out of 50 · profile subject",
    forecastUnitSat: "out of 1600 · SAT composite",
    forecastUnitIelts: "band · overall score",
    forecastTrend: "over 7 days",
    checkpoint: "Check-in",
    checkpointDue: "Time to refresh the plan: a short 5-question check.",
    checkpointFresh: "Plan is up to date. Next check-in in",
    checkpointCta: "Take the check-in",
    hours: "Study hours",
    hoursWeek: "this week",
    streakTitle: "Streak",
    streakUnit: "days in a row",
    eloTitle: "ELO rating",
    tasksTitle: "Assignments from your teacher",
    tasksEmpty: "No assignments yet. Teachers hand them out from their panel.",
    taskDue: "by",
    continueTopic: "Continue",
    startTopic: "Start",
    repeatTopic: "Review",
    goalEnt: "Goal: UNT",
    goalOlymp: "Goal: olympiad",
    goalSchool: "Goal: school",
    daysToExam: "days to the exam",
    activity: "Activity",
    solved: "problems solved",
    rivalAhead: "to",
    rivalCatch: "Catch",
    noDiag: "Take the diagnostic first — we'll build your knowledge map.",
    goDiag: "Take the diagnostic",
  },
  learn: {
    theory: "Theory",
    example: "Worked example",
    practiceCta: "To the problems",
    materials: "Teacher's materials",
    backToMap: "Back to the map",
    customEmpty: "This topic was added by your teacher. Materials will appear here.",
  },
  practice: {
    title: "Practice",
    checkTitle: "Check-in",
    hintBtn: "Hint",
    answerBtn: "Answer",
    nextQ: "Next",
    finish: "Finish",
    explain: "Solution",
    sessionDone: "Session complete",
    accuracy: "Accuracy",
    eloChange: "ELO",
    masteryUp: "Topic progress",
    forecastNow: "Forecast",
    toDash: "To dashboard",
    more: "More problems",
    stuckTitle: "This topic seems to be a grind",
    stuckBody: "That's normal. You can bring in a real teacher for exactly this topic — spot help, not a subscription.",
    stuckCta: "I want a session with a teacher",
    stuckLater: "I'll keep trying",
    stuckSent: "Request sent. Your teacher will see it in their panel.",
  },
  lead: {
    title: "League",
    sub: "Rating updates for solved problems. Harder ones give more.",
    tabElo: "By ELO",
    tabHours: "By hours",
    you: "you",
    hoursTotal: "study hours",
    catchUp: "To the next spot",
  },
  teacher: {
    title: "Teacher panel",
    sub: "Grade 7 “B”, mathematics",
    students: "Students",
    avgElo: "Average ELO",
    activeToday: "Active today",
    weakTopics: "Slipping topics",
    colName: "Student",
    colElo: "ELO",
    colProgress: "Progress",
    colHours: "Hours",
    colStreak: "Streak",
    colLast: "Last seen",
    colStatus: "Status",
    daysAgo: "d ago",
    stuckOn: "stuck on:",
    ok: "on track",
    give: "Assign work",
    giveTitle: "New assignment",
    giveName: "Title",
    giveNamePh: "e.g. solve 10 discriminant problems",
    giveTopic: "Topic",
    giveDue: "Due date",
    giveNote: "Note (optional)",
    giveDone: "Assigned — it will appear in students' dashboards.",
    addTopicTitle: "Add a topic",
    addTopicName: "Topic name",
    addTopicDesc: "Short description",
    addTopicDone: "Topic added to students' knowledge maps.",
    addMatTitle: "Attach material",
    addMatName: "Title",
    addMatUrl: "Link",
    addMatDone: "The material will appear on the topic page.",
    requests: "Help requests",
    requestsEmpty: "Empty for now. When a student gets stuck and asks for help, the request shows up here.",
    heat: "Class map by topic",
    heatHint: "Row — student, column — topic. The darker the cell, the weaker the topic.",
  },
  parent: {
    title: "Parent digest",
    sub: "Once a week, in plain words, no jargon.",
    weekOf: "Week of",
    copy: "Copy text",
    copied: "Copied",
    generate: "Refresh digest",
    tpl: {
      greeting: "Hello! A short summary of the week:",
      streakGood: "has been studying {n} days in a row without missing",
      streakNone: "studied with breaks this week — that's fine, the key is getting back on rhythm",
      hours: "logged {h} of focused problem time this week",
      improved: "clear progress in: {topics}",
      weak: "worth extra attention: “{topic}” — it's going slower than the rest",
      forecast: "current profile-math forecast is about {n} of 50 points ({d} vs last week)",
      plan: "plan for the coming days: {topics}",
      noData: "Not much data yet: after the first diagnostic the digest gets detailed.",
    },
  },
  profile: {
    title: "Profile",
    grade: "Grade",
    goal: "Goal",
    switchGoal: "Change goal",
    switchTitle: "Change the goal — keep the progress",
    switchBody: "The knowledge map is shared. Everything you've mastered carries over to the new goal — no starting from scratch.",
    switchDone: "Goal updated. Topics carried over:",
    lang: "Interface language",
    achievements: "Achievements",
    achList: {
      firstDiag: { t: "First map", d: "diagnostic completed" },
      streak3: { t: "Three in a row", d: "streak of 3+" },
      elo1000: { t: "Club 1000", d: "ELO above 1000" },
      mastered: { t: "First topic", d: "a topic mastered to 70%+" },
      tasks20: { t: "The twenty", d: "20 problems solved" },
      checkin: { t: "In touch", d: "check-in completed" },
    },
    locked: "not unlocked yet",
    reset: "Reset all data",
    resetConfirm: "Sure? Progress, ELO and history will be wiped from this device.",
    resetYes: "Yes, reset",
    dataNote: "MVP data lives locally in your browser — no signup needed.",
  },
  feedback: {
    correct: ["Clean!", "Yes — exactly.", "Level rising.", "Textbook.", "Strong."],
    wrong: ["Not yet — see the solution.", "Nope. Breakdown below.", "Mistakes teach best. Here's how:", "Close, but no. Look:"],
  },
  roles: {
    pick: "Who are you?",
    pickSub: "This decides what you see next",
    student: { t: "Student", d: "I study, prepare for my goal and track my progress" },
    teacher: { t: "Teacher", d: "I run a class, set work and watch students' progress" },
    parent: { t: "Parent", d: "I check how my child is doing" },
    switch: "Switch role",
    signedAs: "Signed in as",
  },
  codes: {
    yourCode: "Your student code",
    yourCodeHint: "Give this code to your teacher or parent so they can find your progress.",
    classCode: "Class code",
    classCodeHint: "Read this code out to your students — it's how they join your class.",
    joinTitle: "Join a class",
    joinHint: "Enter the code your teacher gave you.",
    joinPh: "CL-XXXX",
    joinOk: "Done — you're in the class",
    joinFail: "No class with that code. Check it again.",
    notInClass: "You haven't joined a class yet",
    notInClassHint: "Until you join, your teacher can't see your progress or set you work.",
    joinCta: "Enter a class code",
    linkTitle: "Link your child",
    linkHint: "Enter the code your child sees in their profile.",
    linkPh: "ST-XXXX",
    linkOk: "Child linked",
    linkFail: "No student found with that code",
    linkCta: "Link by code",
    noChild: "No child linked yet",
    noChildHint: "Ask your child for the code in their profile and you'll see their digest.",
    changeChild: "Change child",
    copy: "Copy",
    copied: "Copied",
    copyLink: "Copy link",
    linkHintTeacher: "The link works on any device — send it to the class chat, the code is baked in.",
    shareChild: "Link for a parent",
    shareChildHint: "Send it to your parent — they'll see your real progress from their own phone.",
    recovery: "Recovery key",
    recoveryHint: "Save this link. It brings your profile back on any device, even after clearing the browser.",
    linkCopied: "Link copied",
    joinedByLink: "You joined the class through the link",
    restoredByLink: "Profile restored",
    childByLink: "Child's data received",
    demoHint: "No code? Enter CL-DEMO — that's the demo class.",
  },
  subjects: {
    title: "Subjects",
    pick: "What will you study?",
    pickHint: "Pick several if you like — progress is tracked per subject.",
    add: "Add a subject",
    active: "Currently studying",
    switchTo: "Switch subject",
    empty: "No subject selected yet",
  },
  teacherSetup: {
    title: "Teacher profile",
    name: "What's your name?",
    namePh: "Full name",
    school: "School",
    schoolPh: "e.g. NIS No. 1",
    className: "Class",
    classNamePh: "e.g. 9 «B»",
    subject: "Subject",
    create: "Create the class",
    rosterEmpty: "Nobody here yet. Read the class code out to your students and they'll appear automatically.",
  },
  parentSetup: {
    title: "Parent profile",
    name: "What's your name?",
    namePh: "Name",
    create: "Continue",
  },
  assistant: {
    title: "AI mentor",
    sub: "Reads your numbers and tells you what to do next",
    open: "Ask the mentor",
    adviceTitle: "What I see right now",
    ask: "What to ask",
    watch: "Watch a video on this topic",
    toTopic: "Go to the topic",
    thinking: "Reading your data…",
    empty: "Take the diagnostic and I'll have something to tell you.",
    basis: "Every line is derived from your answers, rating and study time — nothing invented.",
    placeholder: "Ask anything: explain a topic, what to do today…",
    again: "Ask something else",
  },
  inbox: {
    title: "Messages",
    sub: "Deadline reminders and nudges from your mentor",
    empty: "Quiet for now. Mock-test reminders and nudges to study will appear here.",
    markRead: "Mark read",
    unread: "new",
  },
  mock: {
    title: "Mock test",
    sub: "A check over what you've already studied",
    scheduled: "Mock test scheduled",
    dueIn: "left",
    dueToday: "last day is today",
    overdue: "overdue",
    start: "Start the mock test",
    questions: "questions",
    noHints: "No hints — just like the real exam.",
    resultTitle: "Mock test result",
    correct: "Correct answers",
    mistakes: "Mistakes",
    fixTitle: "Work on mistakes",
    fixSub: "The exact problems you missed. Review them while your reasoning is fresh.",
    fixStart: "Review mistakes",
    fixDone: "Mistakes reviewed",
    noneYet: "A mock test appears once you've worked through at least two topics.",
    bbTimer: "Time left",
    bbMark: "Mark for review",
    bbMarked: "Marked",
    bbNav: "All questions",
    bbReview: "Review your answers",
    bbReviewSub: "You can go back to any question before submitting.",
    bbAnswered: "answered",
    bbUnanswered: "unanswered",
    bbSubmit: "Submit test",
    bbConfirm: "Submit now?",
    bbConfirmBody: "Answers can't be changed after submitting.",
    bbBack: "Back",
    bbNext: "Next",
    bbFinishReview: "Go to review",
    bbTimeUp: "Time is up — the test was submitted automatically.",
    bbDirections: "Real exam format: the timer runs, there are no hints, and you can revisit any question before submitting.",
    bbStart: "Start",
    bbQuestion: "Question",
    bbOf: "of",
    dueOn: "Scheduled for",
    history: "Past tests",
  },
  lesson: {
    reading: "Summary",
    readingSub: "The whole topic on one page",
    section: "Section",
    prev: "Back",
    next: "Next",
    toSummary: "To the summary",
    resume: "Resume the lesson",
    resumeSub: "You stopped here",
    finished: "Lesson complete",
    minutes: "min read",
    video: "Video on this topic",
    resources: "Where else to read",
    videoHint: "Opens a YouTube search for this topic",
  },
  auth: {
    emailLabel: "Email",
    emailPh: "you@mail.kz",
    emailHint: "Lets you get your profile back if you clear the browser or switch devices.",
    emailOptional: "optional",
    haveAccount: "Studied here before?",
    signIn: "Sign in by email",
    signInTitle: "Sign in by email",
    signInHint: "Enter the email you registered with.",
    signInFail: "No profile with that email on this device.",
    signInOk: "Welcome back",
    localNote: "Your profile lives in this browser. With an email you can restore it after clearing data.",
  },
  gates: {
    needStart: "Create a profile first",
  },
};
